permissions:
  contents: write

name: Deploy Eleventy → GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build with Eleventy
      - name: Build Eleventy
        run: npm run build

      # 5) Deploy the output folder (_site) to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
